# Generated by Django 6.0.2 on 2026-03-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Autor')),
                ('naturalidade', models.CharField(blank=True, help_text='Ex: Pereiras-SP', max_length=100)),
                ('biografia', models.TextField(blank=True, verbose_name='Breve Biografia')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Livro')),
                ('ano_publicacao', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, verbose_name='ISBN/Registro')),
                ('e_digital', models.BooleanField(default=False, verbose_name='Possui Versão Digital?')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='livros_digitais/')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado')], default='disponivel', max_length=20)),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Estante A, Prateleira 2', max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='acervo.autor')),
            ],
        ),
    ]
